# For a standalone version should be:
#
# fixtures:
#   forge_modules:
#     stdlib:
#       repo: "puppetlabs/stdlib"
#       ref:  "4.9.0"
#     filemapper:
#       repo: "adrien/filemapper"
#       ref:  "1.1.3"
#   symlinks:
#     l23network: "#{source_dir}"

fixtures:
  symlinks:
    l23network: "#{source_dir}"
    stdlib: "#{source_dir}/../stdlib"
    sysctl: "#{source_dir}/../sysctl"
    filemapper: "#{source_dir}/../filemapper"
    vswitch: "#{source_dir}/../vswitch"
