fixtures:
  repositories:
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'filemapper': 'git://github.com/adrienthebo/puppet-filemapper.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
  symlinks:
    'l23network': "#{source_dir}"