fixtures:
  repositories:
    erlang:
      repo: "https://github.com/garethr/garethr-erlang.git"
  symlinks:
    rabbitmq: "#{source_dir}"
    stdlib: "#{source_dir}/../stdlib"
    apt: "#{source_dir}/../apt"
    staging: "#{source_dir}/../staging"
