language: ruby
bundler_args: --without development
before_install:
  - gem update --system 2.1.11
  - gem --version
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.4.0"
notifications:
  email: false
