fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "keystone": "git://github.com/puppetlabs/puppetlabs-keystone.git"
    "mysql":
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: 'origin/0.x'
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "sysctl": "git://github.com/duritong/puppet-sysctl.git"
    "rabbitmq": "git://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    'inifile':  'git://github.com/cprice-puppet/puppetlabs-inifile'
  symlinks:
    "nova": "#{source_dir}"
