fixtures:
  repositories:
    'cinder': 'git://github.com/stackforge/puppet-cinder.git'
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql':
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/2.2.x'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'postgresql':
      repo: "git://github.com/puppetlabs/puppet-postgresql.git"
      ref: '2.5.0'
    'qpid': 'git://github.com/dprince/puppet-qpid.git'
    'rabbitmq': 'git://github.com/puppetlabs/puppetlabs-rabbitmq.git'
    'apt': 'git://github.com/puppetlabs/puppetlabs-apt.git'
    'staging': 'git://github.com/nanliu/puppet-staging.git'
    'erlang' : 'https://github.com/garethr/garethr-erlang.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
  symlinks:
    'nova': "#{source_dir}"
