name    'puppetlabs-nova'
version '0.2.0'
source  'https://github.com/puppetlabs/puppetlabs-nova'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Nova Module'
description 'Puppet module to install and configure the OpenStack Nova compute service'
project_page 'https://github.com/puppetlabs/puppetlabs-nova'

## Add dependencies, if any:
dependency 'puppetlabs/apt', '>= 0.0.3'
dependency 'puppetlabs/glance', '>= 0.2.0'
dependency 'puppetlabs/keystone', '>= 0.2.0'
dependency 'puppetlabs/mysql', '>= 0.3.0'
dependency 'puppetlabs/rabbitmq', '>= 2.0.0'
dependency 'puppetlabs/stdlib', '>= 2.3.0'
dependency 'duritong/sysctl', '>= 0.0.1'
