fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "1.2.0"
  symlinks:
    ssh: "#{source_dir}"
