#!/bin/bash
#
# Script to make a HAProxy capable of monitoring the Swift proxy backends status.
# This script checks the Swift healthcheck report via given Swift endpoint with
# given connect timeout and reports an HTTP 200 OK, if the result is OK.
# If the result was not OK or the endpoint was not reachable,
# it would report an HTTP 503 Error.
#
# Author: Bogdan Dobrelya <bdobrelia@mirantis.com>
#

if [[ $1 == '-h' || $1 == '--help' ]];then
    echo "Usage: $0 <swift_endpoint> <connect_timeout>"
    exit
fi

# Remove trailing slash
url=`echo $1 | sed 's#/*$##'`

result=`/usr/bin/curl --connect-timeout ${2} -XGET ${1}/healthcheck 2>/dev/null`
rc=$?

if [[ $result == "OK" && $rc == 0 ]] ; then
    # Swift healthcheck is OK and endpoint is reachable
    # return HTTP 200. Shell return-code is 0
    echo -en "HTTP/1.1 200 OK\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n"
    echo -en "Content-Length: 5\r\n"
    echo -en "\r\n"
    echo -en "OK.\r\n"
    sleep 0.1
    exit 0
else
    # Swift healthcheck failed or endpoint was not reachable,
    # return HTTP 503. Shell return-code is 1
    echo -en "HTTP/1.1 503 Service Unavailable\r\n"
    echo -en "Content-Type: text/plain\r\n"
    echo -en "Connection: close\r\n"
    echo -en "Content-Length: 8\r\n"
    echo -en "\r\n"
    echo -en "Error.\r\n"
    sleep 0.1
    exit 1
fi
