name         'camptocamp-openssl'
version      '0.3.1'
dependency   'puppetlabs/stdlib', '>= 2.0.0'
source       'https://github.com/camptocamp/puppet-openssl'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp OpenSSL Module'
description  'OpenSSL Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-openssl'
