#!/bin/bash

OCF_RESKEY_enable_rpc_ha_default=true
: ${OCF_RESKEY_enable_rpc_ha=${OCF_RESKEY_enable_rpc_ha_default}}

read -d '' EXTENDED_OCF_PARAMS << EOF
<parameter name="enable_rpc_ha" unique="0" required="0">
<longdesc lang="en">
Set ha-mode=all policy for RPC queues. Note that Ceilometer queues are not
affected by this flag and are always assigned ha-mode=all policy.
</longdesc>
<shortdesc lang="en">Set ha-mode=all policy for RPC queues</shortdesc>
<content type="boolean" default="${OCF_RESKEY_enable_rpc_ha_default}" />
</parameter>
EOF

upstream_rabbitmq_ocf_script="$(dirname $0)/rabbitmq-server-upstream"
. $upstream_rabbitmq_ocf_script
