fixtures:
  repositories:
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.1'
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
    postgresql: git://github.com/puppetlabs/puppetlabs-postgresql.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    rabbitmq: 'git://github.com/puppetlabs/puppetlabs-rabbitmq'
  symlinks:
    'openstacklib': "#{source_dir}"
