name    'puppetlabs-openstacklib'
version '5.0.0-devel'
source  'https://github.com/stackforge/puppet-openstacklib'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs OpenStackLib Module'
description 'Puppet module library to expose common functionality between OpenStack modules'
project_page 'https://launchpad.net/puppet-openstacklib'

dependency 'puppetlabs/mysql',  '>=2.2.0 <3.0.0'
dependency 'puppetlabs/stdlib', '>=3.2.0'
