name    'puppet-vswitch'
version '0.1.0'
source  'https://github.com/ekarlso/puppet-vswitch'
author  'Endre Karlson, Dan Bode'
license 'Apache License 2.0'
summary 'Puppet module for OpenVSwitch and other vSwitchs'
description 'Puppet module to install and configure the OpenVSwitch and other vSwitchs'
project_page 'https://github.com/ekarlso/puppet-vswitch'
