fixtures:
  repositories:
    "apache": "git://github.com/puppetlabs/puppetlabs-apache.git"
    "concat": "git://github.com/ripienaar/puppet-concat.git"
    "firewall": "git://github.com/puppetlabs/puppetlabs-firewall.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "horizon": "#{source_dir}"
