name    'puppetlabs-horizon'
version '4.1.0'
source  'https://github.com/stackforge/puppet-horizon'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Horizon Module'
description  'Puppet module to install and configure the OpenStack Horizon dashboard'
project_page 'https://launchpad.net/puppet-horizon'

dependency 'puppetlabs/apache', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'saz/memcached', '>= 2.0.2 <3.0.0'
