fixtures:
  symlinks:
    ceilometer: "#{source_dir}/../ceilometer"
    pacemaker: "#{source_dir}/../pacemaker"
    inifile: "#{source_dir}/../inifile"
    nova: "#{source_dir}/../nova"
    stdlib: "#{source_dir}/../stdlib"
    vmware: "#{source_dir}"
    oslo: "#{source_dir}/../oslo"
