fixtures:
  repositories:
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'concat': 'https://github.com/ripienaar/puppet-concat.git'
  symlinks:
    'twemproxy': "#{source_dir}"
