#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/fuel-rabbit-fence" ] || [ -e "/etc/init/fuel-rabbit-fence.conf" ]; then
	if [ ! -e "/etc/init/fuel-rabbit-fence.conf" ]; then
		update-rc.d fuel-rabbit-fence defaults >/dev/null
	fi
	invoke-rc.d fuel-rabbit-fence start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f fuel-rabbit-fence remove >/dev/null || exit $?
# End automatically added section
