#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/fuel-rabbit-fence" ] || [ -e "/etc/init/fuel-rabbit-fence.conf" ]; then
	invoke-rc.d fuel-rabbit-fence stop || exit $?
fi
# End automatically added section
