rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: 'bundle exec rake spec'
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.6.1
matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.25
    - rvm: 2.1.0
      env: PUPPET_VERSION=2.7.25
