name 'cprice404-inifile'
version '0.0.3'
source 'git://github.com/cprice-puppet/puppetlabs-inifile.git'
author 'Chris Price'
description 'Resource types for managing settings in INI files'
summary 'Resource types for managing settings in INI files'
license 'Apache'
project_page 'https://github.com/cprice-puppet/puppetlabs-inifile'
