require 'digest/md5'

Puppet::Type.newtype(:sysfs_config_value, :doc => <<-eos
Create a sysfsutils config file with defined values
eos
) do

  ensurable

  newparam :name, :namevar => true do
    desc 'The path to the config file'
  end

  newparam :sysfs do
    desc 'Path to the SysFS nodes to be updated'
  end

  newparam :exclude do
    desc 'Path to the SysFS nodes to be excluded'
  end

  newparam :value do
    desc 'Set the SysFS nodes to this value'
  end

  newproperty :content do
    desc 'Content of the config file. Should be autogenerated unless overriden.'

    def should_to_s(value)
      "(md5)#{Digest::MD5.hexdigest value}"
    end

    def is_to_s(value)
      "(md5)#{Digest::MD5.hexdigest value}"
    end
  end

  def generate_content?
    return false if self[:content]
    !self[:sysfs].nil? and !self[:value].nil?
  end

  def validate
    fail 'You should privide either "sysfs" and "value" to generate content or the "content" itself!' unless self[:content] or generate_content?
  end

end
