fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "concat":
      "repo": "git://github.com/puppetlabs/puppetlabs-concat.git"
      "ref": "1.2.1"
    "inifile":  "git://github.com/puppetlabs/puppetlabs-inifile"
    "keystone": "git://github.com/stackforge/puppet-keystone.git"
    "memcached": "git://github.com/saz/puppet-memcached.git"
    "openstacklib": "git://github.com/stackforge/puppet-openstacklib.git"
    "rsync": "git://github.com/puppetlabs/puppetlabs-rsync.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "xinetd": "git://github.com/puppetlabs/puppetlabs-xinetd.git"
  symlinks:
    "swift": "#{source_dir}"
