name    'puppetlabs-swift'
version '0.1.0'
source  'https://github.com/puppetlabs/puppetlabs-swift'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Swift Module'
description 'Puppet module to install and configure the OpenStack Swift storage service'
project_page 'https://github.com/puppetlabs/puppetlabs-swift'

## Add dependencies, if any:
dependency 'puppetlabs/keystone', '>= 0.1.0'
dependency 'puppetlabs/mysql', '>= 0.3.0'
dependency 'puppetlabs/rsync', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 2.3.0'
dependency 'ripienaar/concat', '>= 0.1.0'
dependency 'saz/memcached', '>= 2.0.1'
dependency 'saz/ssh', '>= 1.0.2'
