source 'https://rubygems.org'
# this is used to bundle install librarian puppet for the deployment folder

group :development, :test do
  gem 'librarian-puppet-simple', :require => false
end

if ENV['PUPPET_GEM_VERSION']
    gem 'puppet', ENV['PUPPET_GEM_VERSION']
else
    gem 'puppet', '~> 3.8.0'
end

# vim:ft=ruby
