#!/usr/bin/env ruby
#^syntax detection
# See https://github.com/bodepd/librarian-puppet-simple for additional docs
#
# Important information for fuel-library:
# With librarian-puppet-simple you *must* remove the existing folder from the
# repo prior to trying to run librarian-puppet as it will not remove the folder
# for you and you may run into some errors.
#
############
# Examples #
############
# From git repo
#  mod 'stdlib',
#    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
#    :ref => '4.6.x'
#
# From tarbal
#  mod 'stdlib',
#    :tarbal => 'https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz'
#
#

# Pull in puppetlabs-stdlib
mod 'stdlib',
    :git => 'https://github.com/fuel-infra/puppetlabs-stdlib.git',
    :ref => '4.9.0'

# Pull in puppetlabs-concat
mod 'concat',
    :git => 'https://github.com/fuel-infra/puppetlabs-concat.git',
    :ref => '1.2.3'

# Pull in puppetlabs-inifile
mod 'inifile',
    :git => 'https://github.com/fuel-infra/puppetlabs-inifile.git',
    :ref => '1.4.2'

# Pull in puppetlabs-xinetd
mod 'xinetd',
    :git => 'https://github.com/fuel-infra/puppetlabs-xinetd.git',
    :ref => '1.5.0'

# Pull in saz-ssh
mod 'ssh',
    :git => 'https://github.com/fuel-infra/saz-ssh.git',
    :ref => 'v2.8.1'

# Pull in puppetlabs-ntp
mod 'ntp',
    :git => 'https://github.com/fuel-infra/puppetlabs-ntp.git',
    :ref => '4.0.0'

# Pull in puppetlabs-apache
mod 'apache',
    :git => 'https://github.com/fuel-infra/puppetlabs-apache.git',
    :ref => '1.6.0'

# Pull in puppetlabs-apt
mod 'apt',
    :git => 'https://github.com/fuel-infra/puppetlabs-apt.git',
    :ref => '2.2.0'

# Pull in puppetlabs-firewall
mod 'firewall',
    :git => 'https://github.com/fuel-infra/puppetlabs-firewall.git',
    :ref => '1.2.0'

# Pull in saz-memcached
mod 'memcached',
    :git => 'https://github.com/fuel-infra/puppet-memcached.git',
    :ref => 'v2.5.0'

# Pull in duritong-sysctl
mod 'sysctl',
    :git => 'https://github.com/fuel-infra/puppet-sysctl.git',
    :ref => 'v0.0.11'

# Pull in nanliu-staging
mod 'staging',
    :git => 'https://github.com/fuel-infra/puppet-staging.git',
    :ref => '1.0.4'

# Pull in puppetlabs-vcsrepo
mod 'vcsrepo',
    :git => 'https://github.com/fuel-infra/puppetlabs-vcsrepo.git',
    :ref => '1.3.1'

# Pull in puppetlabs-postgresql
mod 'postgresql',
    :git => 'https://github.com/fuel-infra/puppetlabs-postgresql.git',
    :ref => '4.0.0'

# Pull in puppet-openstacklib
mod 'openstacklib',
    :git => 'https://github.com/fuel-infra/puppet-openstacklib.git',
    :ref => 'master'

# Pull in puppet-keystone
mod 'keystone',
    :git => 'https://github.com/fuel-infra/puppet-keystone.git',
    :ref => 'master'

# Pull in puppet-neutron
mod 'neutron',
    :git => 'https://github.com/fuel-infra/puppet-neutron.git',
    :ref => 'master'

# Pull in puppet-nova
mod 'nova',
    :git => 'https://github.com/fuel-infra/puppet-nova.git',
    :ref => 'master'

# Pull in puppet-heat
mod 'heat',
    :git => 'https://github.com/fuel-infra/puppet-heat.git',
    :ref => 'master'

# Pull in puppet-horizon
mod 'horizon',
    :git => 'https://github.com/fuel-infra/puppet-horizon.git',
    :ref => 'master'

# Pull in puppet-glance
mod 'glance',
    :git => 'https://github.com/fuel-infra/puppet-glance.git',
    :ref => 'master'

# Pull in puppet-swift
mod 'swift',
    :git => 'https://github.com/fuel-infra/puppet-swift.git',
    :ref => 'master'

# Pull in puppet-ceilometer
mod 'ceilometer',
    :git => 'https://github.com/fuel-infra/puppet-ceilometer.git',
    :ref => 'master'

# Pull in openstack-cinder
mod 'cinder',
    :git => 'https://github.com/fuel-infra/openstack-cinder.git',
    :ref => 'master'

# Pull in puppet-sahara
mod 'sahara',
    :git => 'https://github.com/fuel-infra/puppet-sahara.git',
    :ref => 'master'

# Pull in puppet-openssl
mod 'openssl',
    :git => 'https://github.com/fuel-infra/puppet-openssl.git',
    :ref => '1.3.10-mos-rc2'

# Pull in puppetlabs-mongodb
mod 'mongodb',
    :git => 'https://github.com/fuel-infra/puppetlabs-mongodb.git',
    :ref => '0.12.0'

# Pull in puppetlabs-rsync
mod 'rsync',
    :git => 'https://github.com/fuel-infra/puppetlabs-rsync.git',
    :ref => '0.4.0-mos-rc1'

# Pull in puppet-monit
mod 'monit',
    :git => 'https://github.com/fuel-infra/puppet-monit.git',
    :ref => '1.0.0'

# Pull in puppet-filemapper
mod 'filemapper',
    :git => 'https://github.com/fuel-infra/puppet-filemapper.git',
    :ref => '1.1.3-mos-rc1'

# Pull in puppetlabs-tftp
mod 'tftp',
    :git => 'https://github.com/fuel-infra/puppetlabs-tftp.git',
    :ref => '0.2.3'

# Pull in puppet-ironic
mod 'ironic',
    :git => 'https://github.com/fuel-infra/puppet-ironic.git',
    :ref => 'master'

# Pull in puppet-murano
mod 'murano',
    :git => 'https://github.com/fuel-infra/puppet-murano.git',
    :ref => 'master'

# Pull in richardc-datacat
mod 'datacat',
    :git => 'https://github.com/fuel-infra/richardc-datacat.git',
    :ref => '0.5.0'

# Pull in puppet-mcollective
mod 'mcollective',
    :git => 'https://github.com/fuel-infra/puppet-mcollective.git',
    :ref => 'v2.1.1'

# Pull in puppetlabs-rabbitmq
# FIXME(bogdando) We need the 5.3.1-dc0964d. Use the 5.3.2 once released.
mod 'rabbitmq',
    :git => 'https://github.com/fuel-infra/puppetlabs-rabbitmq.git',
    :ref => '5.3.1-mos-rc1'

# Pull in puppetlabs-mysql
mod 'mysql',
    :git => 'https://github.com/fuel-infra/puppetlabs-mysql.git',
    :ref => '3.6.2'

# Pull in michaeltchapman-galera
mod 'galera',
    :git => 'https://github.com/fuel-infra/puppet-galera.git',
    :ref => '0.0.3-rc1'

# Pull in puppet-twemproxy
mod 'twemproxy',
    :git => 'https://github.com/fuel-infra/puppet-twemproxy',
    :ref => '0.1.1'

# Pull in puppet-aodh
mod 'aodh',
    :git => 'https://github.com/fuel-infra/puppet-aodh.git',
    :ref => 'master'
