#!/usr/bin/env ruby
#^syntax detection
# See https://github.com/bodepd/librarian-puppet-simple for additional docs
#
# Important information for fuel-library:
# With librarian-puppet-simple you *must* remove the existing folder from the
# repo prior to trying to run librarian-puppet as it will not remove the folder
# for you and you may run into some errors.
#
############
# Examples #
############
# From git repo
#  mod 'stdlib',
#    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
#    :ref => '4.6.x'
#
# From tarbal
#  mod 'stdlib',
#    :tarbal => 'https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz'
#
#

# Pull in puppetlabs-stdlib
mod 'stdlib',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-stdlib.git',
    :ref => '4.6.0'

# Pull in puppetlabs-concat
mod 'concat',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-concat.git',
    :ref => '1.2.3'

# Pull in puppetlabs-inifile
mod 'inifile',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-inifile.git',
    :ref => '1.1.3'

# Pull in puppetlabs-xinetd
mod 'xinetd',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-xinetd.git',
    :ref => '1.5.0'

# Pull in saz-ssh
mod 'ssh',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/saz-ssh.git',
    :ref => 'v2.8.1'

# Pull in puppetlabs-ntp
mod 'ntp',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-ntp.git',
    :ref => '4.0.0'

# Pull in puppetlabs-apache
mod 'apache',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-apache.git',
    :ref => '1.3.0'

# Pull in puppetlabs-apt
mod 'apt',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-apt.git',
    :ref => '1.8.0'

# Pull in puppetlabs-firewall
mod 'firewall',
    :git => 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-firewall.git',
    :ref => '1.2.0-mos-rc2'
