fixtures:
  repositories:
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'mysql': 'https://github.com/puppetlabs/puppetlabs-mysql.git'
  symlinks:
    'cluster': "#{source_dir}"
    'corosync': "#{source_dir}/../corosync"
    'openstack': "#{source_dir}/../openstack"
    'pacemaker': "#{source_dir}/../pacemaker"
    'pacemaker_wrappers': "#{source_dir}/../pacemaker_wrappers"
