fixtures:
  symlinks:
    cluster: "#{source_dir}"
    corosync: "#{source_dir}/../corosync"
    openstack: "#{source_dir}/../openstack"
    stdlib: "#{source_dir}/../stdlib"
    ntp: "#{source_dir}/../ntp"
    heat: "#{source_dir}/../heat"
    openstacklib: "#{source_dir}/../openstacklib"
    inifile: "#{source_dir}/../inifile"
    mysql: "#{source_dir}/../mysql"
    pacemaker: "#{source_dir}/../pacemaker"
    rabbitmq: "#{source_dir}/../rabbitmq"
    apt: "#{source_dir}/../apt"
    staging: "#{source_dir}/../staging"
    xinetd: "#{source_dir}/../xinetd"
    oslo: "#{source_dir}/../oslo"
