fixtures:
  repositories:
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'cluster': "#{source_dir}"
    'corosync': "#{source_dir}/../corosync"
    'openstack': "#{source_dir}/../openstack"
  repositories:
    pacemaker: 
      repo: "https://review.fuel-infra.org/puppet-modules/puppet-pacemaker.git"
      ref: "0.0.2"
