fixtures:
  symlinks:
    "nailgun": "#{source_dir}"
    "mcollective": "#{source_dir}/../mcollective"
  repositories:
    "rabbitmq": "git://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "staging": "git://github.com/nanliu/puppet-staging.git"
    "erlang": "https://github.com/garethr/garethr-erlang.git"
