name 'Mirantis Inc-puppet'
version '0.0.1'

author 'Mirantis Inc.'
license 'Apache License 2.0'
project_page 'http://mirantis.com'
source 'git@github.com:Mirantis/product.git'
summary 'Mirantis Puppet Master Module'
description 'Module to install puppet master with nginx as frontend'
