name    'saz-memcached'
version '2.5.0'
source 'git://github.com/saz/puppet-memcached.git'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage memcached via Puppet'
project_page 'https://github.com/saz/puppet-memcached'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/firewall', '>= 0.1.0'
