include ::osnailyfacter::cluster_haproxy::cluster_haproxy
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_aodh
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_ceilometer
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_cinder
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_glance
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_heat
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_horizon
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_ironic
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_keystone
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_murano
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_mysqld
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_neutron
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_nova
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_radosgw
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_sahara
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_stats
include ::osnailyfacter::openstack_haproxy::openstack_haproxy_swift
include ::osnailyfacter::openstack_haproxy::openstack_haproxy
