class { '::osnailyfacter::cluster_haproxy::cluster_haproxy': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_aodh': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_ceilometer': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_cinder': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_glance': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_heat': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_horizon': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_ironic': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_keystone': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_murano': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_mysqld': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_neutron': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_nova': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_radosgw': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_sahara': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_stats': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy_swift': }
class { '::osnailyfacter::openstack_haproxy::openstack_haproxy': }
