fixtures:
  repositories:
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile'
    'concat':
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.1'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'postgresql': 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
    'qpid': 'git://github.com/dprince/puppet-qpid.git'
    'rabbitmq':
      repo: 'git://github.com/puppetlabs/puppetlabs-rabbitmq'
      ref: 'origin/2.x'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
  symlinks:
    'sahara': "#{source_dir}"
