name         'puppetlabs-neutron'
version      '4.0.0'
author       'StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Neutron'
description  'Installs and configures OpenStack Neutron (Networking).'
project_page 'https://launchpad.net/puppet-neutron'
source       'https://github.com/stackforge/puppet-neutron'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/nova', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/stdlib', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/vswitch', '>=0.2.0 <1.0.0'
dependency 'duritong/sysctl', '>=0.0.1 <1.0.0'
dependency 'stackforge/openstacklib', '>=5.0.0'
