name    'dprince/qpid'
version '1.0.0'
source 'git://github.com/dprince/puppet-qpid.git'
author 'Dan Prince <dprince@redhat.com>'
license 'Apache'
summary 'Qpid Puppet Module'
description 'This module manages Qpid.'
project_page 'https://github.com/dprince/puppet-qpid'

dependency 'puppetlabs/stdlib', '>= 0.0.1'
