fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "mysql": 
      repo: "git://github.com/puppetlabs/puppetlabs-mysql.git"
      ref:  'origin/0.x'
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "inifile": 'git://github.com/cprice-puppet/puppetlabs-inifile'
  symlinks:
    "keystone": "#{source_dir}"
