fixtures:
  repositories:
    'apache': 'git://github.com/puppetlabs/puppetlabs-apache.git'
    'concat':
      'repo': 'git://github.com/puppetlabs/puppetlabs-concat.git'
      'ref': '1.2.1'
    'apt': 'git://github.com/puppetlabs/puppetlabs-apt.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile'
    'postgresql': 'git://github.com/puppetlabs/puppetlabs-postgresql.git'
  symlinks:
    'keystone': "#{source_dir}"
