name    'puppetlabs-keystone'
version '0.1.0'
source  'git://github.com/puppetlabs/puppetlabs-keystone'
author  'Puppet Labs'
license 'Apache'
summary 'Keystone Puppet Module'
description 'Openstack Keystone module. Tested on Ubuntu'
project_page 'http://github.com/puppetlabs/puppetlabs-keystone'

dependency 'ripienaar/concat', '>= 0.1.0'
dependency 'puppetlabs/mysql', '>= 0.3.0'
dependency 'puppetlabs/apt', '>= 0.0.3'
