name    'puppetlabs-keystone'
version '0.2.0'
source  'git://github.com/puppetlabs/puppetlabs-keystone'
author  'Puppet Labs'
license 'Apache'
summary 'Keystone Puppet Module'
description 'Openstack Keystone module. Tested on Ubuntu and RHEL 6'
project_page 'http://github.com/puppetlabs/puppetlabs-keystone'

dependency 'ripienaar/concat', '>= 0.2.0'
dependency 'puppetlabs/mysql', '>= 0.5.0'
dependency 'puppetlabs/apt', '>= 0.0.4'
