name    'puppetlabs-keystone'
version '3.1.1'
source  'https://github.com/stackforge/puppet-keystone'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Keystone Module'
description 'Puppet module to install and configure the Openstack identity service'
project_page 'https://launchpad.net/puppet-openstack'

dependency 'puppetlabs/apache', '>=0.9.0 <1.0.0'
dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/mysql', '>=0.6.1 <1.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
