fixtures:
  symlinks:
    cobbler: "#{source_dir}"
    openssl: "#{source_dir}/../openssl"
    inifile: "#{source_dir}/../inifile"
    firewall: "#{source_dir}/../firewall"
    stdlib: "#{source_dir}/../stdlib"
    apache: "#{source_dir}/../apache"
    concat: "#{source_dir}/../concat"
    fuel: "#{source_dir}/../fuel"
