fixtures:
  repositories:
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'openssl': 'https://review.fuel-infra.org/puppet-modules/puppet-openssl.git'
    'firewall': 'https://review.fuel-infra.org/puppet-modules/puppetlabs-firewall.git'
  symlinks:
    'cobbler': "#{source_dir}"
