fixtures:
  symlinks:
    cobbler: "#{source_dir}"
    openssl: "#{source_dir}/../openssl"
    inifile: "#{source_dir}/../inifile"
    firewall: "#{source_dir}/../firewall"
    stdlib: "#{source_dir}/../stdlib"
    apache: "#{source_dir}/../apache"
