require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'

PuppetSyntax.exclude_paths ||= []
PuppetSyntax.exclude_paths << "spec/fixtures/**/*"
PuppetSyntax.exclude_paths << "pkg/**/*"
PuppetSyntax.exclude_paths << "vendor/**/*"

Rake::Task[:lint].clear
PuppetLint::RakeTask.new :lint do |config|
  config.ignore_paths = ["spec/**/*.pp", "vendor/**/*.pp"]
  config.fail_on_warnings = false # TODO(aschultz): fix warnings
  config.log_format = '%{path}:%{linenumber}:%{KIND}: %{message}'
  config.disable_checks = [
      "80chars",
      "class_inherits_from_params_class",
      "class_parameter_defaults",
      "only_variable_string",
      "2sp_soft_tabs",
      "hard_tabs",
      "tailing_whitespace",
      "unquoted_file_mode",
      "double_quoted_strings",
      "arrow_alignment",
      "documentation",
      "leading_zero",
      "case_without_default",
   ]
end
