fixtures:
  symlinks:
    openstack: "#{source_dir}"
    apache: "#{source_dir}/../apache"
    apt: "#{source_dir}/../apt"
    concat: "#{source_dir}/../concat"
    stdlib: "#{source_dir}/../stdlib"
    sysctl: "#{source_dir}/../sysctl"
    inifile: "#{source_dir}/../inifile"
    firewall: "#{source_dir}/../firewall"
    openstacklib: "#{source_dir}/../openstacklib"
    horizon: "#{source_dir}/../horizon"
    keystone: "#{source_dir}/../keystone"
    neutron: "#{source_dir}/../neutron"
    nova: "#{source_dir}/../nova"
    heat: "#{source_dir}/../heat"
    glance: "#{source_dir}/../glance"
    ceilometer: "#{source_dir}/../ceilometer"
    cinder: "#{source_dir}/../cinder"
    sahara: "#{source_dir}/../sahara"
    murano: "#{source_dir}/../murano"
    xinetd: "#{source_dir}/../xinetd"
    osnailyfacter: "#{source_dir}/../osnailyfacter"
    l23network: "#{source_dir}/../l23network"
    rsyslog: "#{source_dir}/../rsyslog"
    mysql: "#{source_dir}/../mysql"
    tweaks: "#{source_dir}/../tweaks"
    corosync: "#{source_dir}/../corosync"
    pacemaker: "#{source_dir}/../pacemaker"
    haproxy: "#{source_dir}/../haproxy"
    ceilometer_ha: "#{source_dir}/../ceilometer_ha"
    pacemaker_wrappers: "#{source_dir}/../pacemaker_wrappers"
    mellanox_openstack: "#{source_dir}/../mellanox_openstack"
