fixtures:
  symlinks:
    "apt": "#{source_dir}/../apt"
    "keystone": "#{source_dir}/../keystone"
    "mysql": "#{source_dir}/../mysql"
    "nova": "#{source_dir}/../nova"
    "ceilometer": "#{source_dir}/../ceilometer"
    "neutron": "#{source_dir}/../neutron"
    "glance": "#{source_dir}/../glance"
    "cinder": "#{source_dir}/../cinder"
    "stdlib": "#{source_dir}/../stdlib"
    "sysctl": "#{source_dir}/../sysctl"
    "inifile": "#{source_dir}/../inifile"
    "openstack": "#{source_dir}"
