fixtures:
  repositories:
    'apt': 'https://github.com/puppetlabs/puppetlabs-apt.git'
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'https://github.com/duritong/puppet-sysctl.git'
    'inifile':  'https://github.com/puppetlabs/puppetlabs-inifile.git'
    'firewall':  'https://github.com/puppetlabs/puppetlabs-firewall.git'
    'openstacklib': 'https://review.fuel-infra.org/puppet-modules/puppet-openstacklib.git -b 7.0.0-mos-rc2'
    'keystone': 'https://review.fuel-infra.org/puppet-modules/puppet-keystone.git -b 7.0.0-mos-rc2'
    'neutron': 'https://review.fuel-infra.org/puppet-modules/puppet-neutron.git -b 7.0.0-mos-rc1'
    'nova': 'https://review.fuel-infra.org/puppet-modules/puppet-nova.git -b 7.0.0-mos-rc1'
    'heat': 'https://review.fuel-infra.org/puppet-modules/puppet-heat.git -b 7.0.0-mos-rc1'
    'glance': 'https://review.fuel-infra.org/puppet-modules/puppet-glance.git -b 7.0.0-mos-rc1'
    'ceilometer': 'https://review.fuel-infra.org/puppet-modules/puppet-ceilometer.git -b 7.0.0-mos-rc1'
    'cinder': 'https://review.fuel-infra.org/puppet-modules/openstack-cinder.git -b 7.0.0-mos-rc1'
    'sahara': 'https://review.fuel-infra.org/puppet-modules/puppet-sahara.git -b 7.0.0-mos-rc1'
  symlinks:
    'openstack': "#{source_dir}"
    'osnailyfacter': "#{source_dir}/../osnailyfacter"
    'l23network': "#{source_dir}/../l23network"
    'rsyslog': "#{source_dir}/../rsyslog"
    'mysql': "#{source_dir}/../mysql"
    'murano': "#{source_dir}/../murano"
