fixtures:
  repositories:
    'apache':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppetlabs-apache.git'
      branch: '1.6.0'
    'apt': 'https://github.com/puppetlabs/puppetlabs-apt.git'
    'concat': 'https://github.com/ripienaar/puppet-concat.git'
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'https://github.com/duritong/puppet-sysctl.git'
    'inifile':  'https://github.com/puppetlabs/puppetlabs-inifile.git'
    'firewall':  'https://github.com/puppetlabs/puppetlabs-firewall.git'
    'mysql':  'https://github.com/puppetlabs/puppetlabs-mysql.git'
    'openstacklib':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-openstacklib.git'
      branch: '7.0.0-mos-rc4'
    'horizon':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-horizon.git'
      branch: '7.0.0-mos-rc3'
    'keystone':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-keystone.git'
      branch: '7.0.0-mos-rc3'
    'neutron':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-neutron.git'
      branch: '7.0.0-mos-rc4'
    'nova':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-nova.git'
      branch: '7.0.0-mos-rc2'
    'heat':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-heat.git'
      branch: '7.0.0-mos-rc2'
    'glance':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-glance.git'
      branch: '7.0.0-mos-rc2'
    'ceilometer':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-ceilometer.git'
      branch: '7.0.0-mos-rc2'
    'cinder':
      repo: 'https://review.fuel-infra.org/puppet-modules/openstack-cinder.git'
      branch: '7.0.0-mos-rc2'
    'sahara':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-sahara.git'
      branch: '7.0.0-mos-rc2'
    'murano':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-murano.git'
      branch: '7.0.0-mos-rc1'
    'xinetd':
      repo: 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-xinetd.git'
      branch: '1.5.0'
  symlinks:
    'openstack': "#{source_dir}"
    'osnailyfacter': "#{source_dir}/../osnailyfacter"
    'l23network': "#{source_dir}/../l23network"
    'rsyslog': "#{source_dir}/../rsyslog"
    'tweaks': "#{source_dir}/../tweaks"
    'corosync': "#{source_dir}/../corosync"
    'pacemaker': "#{source_dir}/../pacemaker"
    'haproxy': "#{source_dir}/../haproxy"
