fixtures:
  repositories:
    'apache':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppetlabs-apache.git'
      branch: '1.6.0'
    'apt': 'https://github.com/puppetlabs/puppetlabs-apt.git'
    'concat': 'https://github.com/ripienaar/puppet-concat.git'
    'stdlib': 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'https://github.com/duritong/puppet-sysctl.git'
    'inifile':  'https://github.com/puppetlabs/puppetlabs-inifile.git'
    'firewall':  'https://github.com/puppetlabs/puppetlabs-firewall.git'
    'openstacklib':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-openstacklib.git'
      branch: 'mos-8.0'
    'horizon':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-horizon.git'
      branch: 'mos-8.0'
    'keystone':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-keystone.git'
      branch: '7.0.0-mos-rc2'
    'neutron':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-neutron.git'
      branch: '7.0.0-mos-rc1'
    'nova':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-nova.git'
      branch: '7.0.0-mos-rc1'
    'heat':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-heat.git'
      branch: '7.0.0-mos-rc1'
    'glance':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-glance.git'
      branch: '7.0.0-mos-rc1'
    'ceilometer':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-ceilometer.git'
      branch: '7.0.0-mos-rc1'
    'cinder':
      repo: 'https://review.fuel-infra.org/puppet-modules/openstack-cinder.git'
      branch: '7.0.0-mos-rc1'
    'sahara':
      repo: 'https://review.fuel-infra.org/puppet-modules/puppet-sahara.git'
      branch: '7.0.0-mos-rc1'
  symlinks:
    'openstack': "#{source_dir}"
    'osnailyfacter': "#{source_dir}/../osnailyfacter"
    'l23network': "#{source_dir}/../l23network"
    'rsyslog': "#{source_dir}/../rsyslog"
    'mysql': "#{source_dir}/../mysql"
    'murano': "#{source_dir}/../murano"
    'tweaks': "#{source_dir}/../tweaks"
