fixtures:
  repositories:
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'apache':
      repo: 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-apache.git'
      branch: '1.6.0'
    'concat':
      repo: 'https://review.fuel-infra.org/p/puppet-modules/puppetlabs-concat.git'
      branch: '1.2.3'
  symlinks:
    'osnailyfacter': "#{source_dir}"
    'l23network': "#{source_dir}/../l23network"
