fixtures:
  symlinks:
    osnailyfacter: "#{source_dir}"
    l23network: "#{source_dir}/../l23network"
    stdlib: "#{source_dir}/../stdlib"
    apache: "#{source_dir}/../apache"
    concat: "#{source_dir}/../concat"
    mysql: "#{source_dir}/../mysql"
    cinder: "#{source_dir}/../cinder"
    openstacklib: "#{source_dir}/../openstacklib"
    sysfs: "#{source_dir}/../sysfs"
    oslo: "#{source_dir}/../oslo"
    haproxy: "#{source_dir}/../haproxy"
