source 'https://rubygems.org'

group :development, :test do
  gem 'rake',                    :require => false
  gem 'fakefs',                  :require => false
  gem 'pry',                     :require => false
  gem 'rspec',                   :require => false
  gem 'rspec-puppet',            :require => false
  gem 'puppetlabs_spec_helper',  :require => false
  gem 'puppet-lint',             :require => false
  gem 'webmock', '1.22.6',       :require => false
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet'
end

# vim:ft=ruby
