name    'puppet-quantum'
version '0.2.2'
source  'https://github.com/EmilienM/openstack-quantum-puppet'
author  'Joe Topjian,Endre Karlson,Emilien Macchi,Dan Bode'
license 'Apache License 2.0'
summary 'Puppet module for OpenStack Quantum'
description 'Puppet module to install and configure the OpenStack network service, Quantum'
project_page 'https://github.com/EmilienM/openstack-quantum-puppet'

# Dependencies
dependency 'puppetlabs/mysql', '>= 0.3.0'
dependency 'puppetlabs/nova', '>= 1.0.1'
dependency 'cprice404/inifile', '>= 0.9.0'
dependency 'ekarlso/vswitch', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 2.4.0'
