#!/bin/sh
# managed by puppet
#
# anacron's cron script
#
# This script updates anacron time stamps. It is called through run-parts
# either by anacron itself or by cron.
#
# The script is called "0anacron" to assure that it will be executed
# _before_ all other scripts.

# Uncomment these lines below, if anacron should manage hourly schedules (by default, it does not)
#test -x /usr/sbin/anacron || exit 0
#anacron -u cron.hourly
