fixtures:
  repositories:
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile'
    'concat':
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.2.1'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'sysctl': 'git://github.com/duritong/puppet-sysctl.git'
    'keystone': 'git://github.com/openstack/puppet-keystone.git'
    'openstacklib': 'git://github.com/openstack/puppet-openstacklib.git'
  symlinks:
    'murano': "#{source_dir}"
