fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    file_concat: git://github.com/electrical/puppet-lib-file_concat.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    logstash: "#{source_dir}"
