---
language: ruby
sudo: false
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  allow_failures:
    - env: PUPPET_GEM_VERSION="~> 4.0"
    - env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email: false
