#!/bin/bash
# managed by puppet
#
# Due to bug in logrotate, it always returns 0. Use grep for detect errors;
# exit code 1 is considered a success as no errors were found.

lock() {
    exec 903>/var/lock/fuel-logrotate
    flock -n 903 && return 0 || return 1
}

fail() {
    if [ -z "$1" ]
    then
        MESSAGE="WARNING logrotate failed, no reason provided"
    else
        MESSAGE=$1
    fi
    /usr/bin/logger -t logrotate "${MESSAGE}"
    exit 1
}

unlock() {
    flock -n 903
}

lock || fail "WARNING logrotate flock failed, exiting"

if ! pgrep -x logrotate >/dev/null 2>&1; then
    nice ionice -c3 /usr/sbin/logrotate /etc/logrotate.d/fuel.nodaily >& /tmp/logrotate
    grep -q error /tmp/logrotate
    EXITVALUE=$?
else
    fail "WARNING another logrotate instance is already running, exiting"
fi

if [ $EXITVALUE != 1 ]; then
    fail "ALERT exited abnormally with [$EXITVALUE] (1 was expected)"
    exit 1
fi

unlock
exit 0
