#!/bin/bash
# managed by puppet

lock() {
    exec 903>/var/lock/fuel-logrotate
    flock -n 903 && return 0 || return 1
}

fail() {
    if [ -z "$1" ]
    then
        MESSAGE="WARNING logrotate failed, no reason provided"
    else
        MESSAGE=$1
    fi
    /usr/bin/logger -t logrotate "${MESSAGE}"
    exit 1
}

unlock() {
    flock -n 903
}

lock || fail "WARNING logrotate flock failed, exiting"

if ! pgrep -x logrotate >/dev/null 2>&1; then
    nice ionice -c3 /usr/sbin/logrotate /etc/logrotate.d/fuel.nodaily
    EXITVALUE=$?
else
    fail "WARNING another logrotate instance is already running, exiting"
    exit 1
fi

if [ $EXITVALUE != 0 ]; then
    fail "ALERT exited abnormally with [$EXITVALUE] (0 was expected)"
fi

unlock
exit $EXITVALUE

