#!/bin/bash
# managed by puppet

exec 903>/var/lock/fuel-logrotate
flock -n 903 || \
    ( /usr/bin/logger -t logrotate "WARNING logrotate flock failed, exiting"; exit 1 )

if ! pgrep -x logrotate >/dev/null 2>&1; then
    nice ionice -c3 /usr/sbin/logrotate /etc/logrotate.d/fuel.nodaily
    EXITVALUE=$?
else
    /usr/bin/logger -t logrotate "WARNING another logrotate instance is already running, exiting"
    exit 1
fi

if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE] (0 was expected)"
fi

flock -u 903
exit $EXITVALUE

