name 'dhoppe-nagios'
version '0.0.27'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-nagios'
source 'git://github.com/dhoppe/puppet-nagios'
summary 'Nagios Module'
description 'Nagios Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
dependency 'dhoppe/role', '>=0.0.1'
dependency 'dhoppe/sudo', '>=0.0.1'
