fixtures:
  forge_modules:
    firewall: "puppetlabs/firewall"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    galera: "#{source_dir}"
    pacemaker: "#{source_dir}/../pacemaker"
    tweaks: "#{source_dir}/../tweaks"
