fixtures:
  forge_modules:
    firewall: "puppetlabs/firewall"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    galera: "#{source_dir}"
    tweaks: "#{source_dir}/../tweaks"
    openstack: "#{source_dir}/../openstack"
  repositories:
    pacemaker: 
      repo: "https://review.fuel-infra.org/puppet-modules/puppet-pacemaker.git"
      ref: "0.0.2"
