- id: sahara
  type: puppet
  version: 2.0.0
  groups: [primary-controller, controller]
  condition: "settings:additional_components.sahara.value == true"
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-network-end, horizon]
  cross-depends:
    - name: sahara-db
    - name: sahara-keystone
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/sahara/sahara.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/sahara/sahara_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/sahara/sahara_post.rb

- id: sahara-db
  type: puppet
  version: 2.0.0
  groups: [primary-controller]
  cross-depends:
    - name: /(primary-)?database/
  required_for: [sahara]
  condition: "settings:additional_components.sahara.value == true"
  requires: [primary-database, database]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/sahara/db.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800

- id: sahara-keystone
  type: puppet
  version: 2.0.0
  groups: [primary-controller]
  required_for: [sahara]
  requires: [primary-keystone, keystone]
  cross-depends:
    - name: keystone
  condition: "settings:additional_components.sahara.value == true"
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/sahara/keystone.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800
