fixtures:
  symlinks:
    "mcollective": "#{source_dir}"
    "rabbitmq": "#{source_dir}/../rabbitmq"
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "staging": "git://github.com/nanliu/puppet-staging.git"
    "erlang": "https://github.com/garethr/garethr-erlang.git"
