name    'puppetlabs-haproxy'
version '0.5.0'
source 'git://github.com/puppetlabs/puppetlabs-haproxy'
author 'Puppet Labs'
license 'Apache License, Version 2.0'
summary 'Haproxy Module'
description 'An Haproxy module for Redhat family OSes using Storeconfigs'
project_page 'http://github.com/puppetlabs/puppetlabs-haproxy'

dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/stdlib', '>= 2.4.0'
