name    'enovance-ceilometer'
version '0.0.1'
source 'none'
author 'enovance'
license 'Apache License, Version 2.0'
summary 'Install/configure Openstack Ceilometer'
description 'Install/configure Openstack Ceilometer'
project_page 'https://launchpad.net/ceilometer'

# Dependencies
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'cprice404/inifile', '>= 0.9.0'
dependency 'puppetlabs/mysql', '>= 0.5.0 <1.0.0'
