fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "keystone": "git://github.com/puppetlabs/puppetlabs-keystone.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "rabbitmq": "git://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    'inifile':  'git://github.com/cprice-puppet/puppetlabs-inifile'
  symlinks:
    "glance": "#{source_dir}"
