name    'puppetlabs-glance'
version '4.0.0'
source  'https://github.com/stackforge/puppet-glance'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Glance Module'
description 'Puppet module to install and configure the Openstack Glance image service'
project_page 'https://launchpad.net/puppet-openstack'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/keystone', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/mysql', '>=0.9.0 <3.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
