name    'puppetlabs-glance'
version '0.1.0'
source  'git://github.com/puppetlabs/puppetlabs-glance'
author  'Puppet Labs'
license 'Apache'
summary 'Glance Puppet Module'
description 'Openstack Glance module. Tested on Ubuntu'
project_page 'http://github.com/puppetlabs/puppetlabs-glance'

dependency 'ripienaar/concat', '>= 0.1.0'
dependency 'puppetlabs/keystone', '>= 0.1.0'
dependency 'puppetlabs/mysql', '>= 0.3.0'
dependency 'puppetlabs/stdlib', '>= 2.3.0'
