#!/usr/bin/env ruby
#^syntax detection
# See https://github.com/bodepd/librarian-puppet-simple for additional docs
#
# Important information for fuel-library:
# With librarian-puppet-simple you *must* remove the existing folder from the
# repo prior to trying to run librarian-puppet as it will not remove the folder
# for you and you may run into some errors.
#
############
# Examples #
############
# From git repo
#  mod 'stdlib',
#    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
#    :ref => '4.6.x'
#
# From tarbal
#  mod 'stdlib',
#    :tarbal => 'https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz'
#
#

# Pull in puppet-aodh
mod 'aodh',
    :git => 'https://github.com/fuel-infra/puppet-aodh.git',
    :ref => 'stable/mitaka'

# Pull in puppet-ceilometer
mod 'ceilometer',
    :git => 'https://github.com/fuel-infra/puppet-ceilometer.git',
    :ref => 'stable/mitaka'

# Pull in openstack-cinder
mod 'cinder',
    :git => 'https://github.com/fuel-infra/openstack-cinder.git',
    :ref => 'stable/mitaka'

# Pull in puppet-glance
mod 'glance',
    :git => 'https://github.com/fuel-infra/puppet-glance.git',
    :ref => 'stable/mitaka'

# Pull in puppet-heat
mod 'heat',
    :git => 'https://github.com/fuel-infra/puppet-heat.git',
    :ref => 'stable/mitaka'

# Pull in puppet-horizon
mod 'horizon',
    :git => 'https://github.com/fuel-infra/puppet-horizon.git',
    :ref => 'stable/mitaka'

# Pull in puppet-ironic
mod 'ironic',
    :git => 'https://github.com/fuel-infra/puppet-ironic.git',
    :ref => 'stable/mitaka'

# Pull in puppet-keystone
mod 'keystone',
    :git => 'https://github.com/fuel-infra/puppet-keystone.git',
    :ref => 'stable/mitaka'

# Pull in puppet-openstacklib
mod 'openstacklib',
    :git => 'https://github.com/fuel-infra/puppet-openstacklib.git',
    :ref => 'stable/mitaka'

# Pull in puppet-neutron
mod 'neutron',
    :git => 'https://github.com/fuel-infra/puppet-neutron.git',
    :ref => 'stable/mitaka'

# Pull in puppet-nova
mod 'nova',
    :git => 'https://github.com/fuel-infra/puppet-nova.git',
    :ref => 'stable/mitaka'

# Pull in puppet-murano
mod 'murano',
    :git => 'https://github.com/fuel-infra/puppet-murano.git',
    :ref => 'stable/mitaka'

# Pull in puppet-sahara
mod 'sahara',
    :git => 'https://github.com/fuel-infra/puppet-sahara.git',
    :ref => 'stable/mitaka'

# Pull in puppet-swift
mod 'swift',
    :git => 'https://github.com/fuel-infra/puppet-swift.git',
    :ref => 'stable/mitaka'
