#!/usr/bin/env ruby
#^syntax detection
# See https://github.com/bodepd/librarian-puppet-simple for additional docs
#
# Important information for fuel-library:
# With librarian-puppet-simple you *must* remove the existing folder from the
# repo prior to trying to run librarian-puppet as it will not remove the folder
# for you and you may run into some errors.
#
############
# Examples #
############
# From git repo
#  mod 'stdlib',
#    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
#    :ref => 'stable/mitaka'
#
# From tarbal
#  mod 'stdlib',
#    :tarbal => 'https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.6.0.tar.gz'
#
#

# Pull in puppet-aodh
mod 'aodh',
    :git => 'https://github.com/fuel-infra/puppet-aodh.git',
    :ref => '563010f1912dd6850a48153c9d0da9fb92c0e6a2'

# Pull in puppet-ceilometer
mod 'ceilometer',
    :git => 'https://github.com/fuel-infra/puppet-ceilometer.git',
    :ref => '2ad139fe16fbd673470366cb49717ae0e5de2e6f'

# Pull in openstack-cinder
mod 'cinder',
    :git => 'https://github.com/fuel-infra/openstack-cinder.git',
    :ref => 'fa017f57f814d1fec6daee71f4e3257fb6c471de'

# Pull in puppet-glance
mod 'glance',
    :git => 'https://github.com/fuel-infra/puppet-glance.git',
    :ref => '9b06a7c8c25a5bd11e0257ea39c7a9680fbac9ab'

# Pull in puppet-heat
mod 'heat',
    :git => 'https://github.com/fuel-infra/puppet-heat.git',
    :ref => 'a6ce6ef92f755ffea3e68a3c2f5c355a4bc3654c'

# Pull in puppet-horizon
mod 'horizon',
    :git => 'https://github.com/fuel-infra/puppet-horizon.git',
    :ref => '77cfadf139b946dacf3b7eb245cd2c0eed878b35'

# Pull in puppet-ironic
mod 'ironic',
    :git => 'https://github.com/fuel-infra/puppet-ironic.git',
    :ref => 'd244370d37255eb9400e718f42c8783bfbc339ab'

# Pull in puppet-keystone
mod 'keystone',
    :git => 'https://github.com/fuel-infra/puppet-keystone.git',
    :ref => 'd76dbaa6e6b521d7e2567745d7c571f23cad2b71'

# Pull in puppet-openstacklib
mod 'openstacklib',
    :git => 'https://github.com/fuel-infra/puppet-openstacklib.git',
    :ref => 'aafb9b05dac6aedf69f1317acf50d4ec851bbbd6'

# Pull in puppet-neutron
mod 'neutron',
    :git => 'https://github.com/fuel-infra/puppet-neutron.git',
    :ref => '879e8d698e07dca23b48b2ade6ffd910626de9ed'

# Pull in puppet-nova
mod 'nova',
    :git => 'https://github.com/fuel-infra/puppet-nova.git',
    :ref => '1d236a87c38f1506182134d0d6726432c3d240d6'

# Pull in puppet-murano
mod 'murano',
    :git => 'https://github.com/fuel-infra/puppet-murano.git',
    :ref => 'e8da90ba045310670d275e7d6b09461c91d8e201'

# Pull in puppet-sahara
mod 'sahara',
    :git => 'https://github.com/fuel-infra/puppet-sahara.git',
    :ref => '5359ed0ddedba65c2edc1766904e81f079cc9d5a'

# Pull in puppet-swift
mod 'swift',
    :git => 'https://github.com/fuel-infra/puppet-swift.git',
    :ref => '17d1411b01896deda0d96130f25a978b91009b8f'
